/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/feed/': RouteRecordInfo<'/feed/', '/feed', Record<never, never>, Record<never, never>>,
    '/friends/': RouteRecordInfo<'/friends/', '/friends', Record<never, never>, Record<never, never>>,
    '/girls/': RouteRecordInfo<'/girls/', '/girls', Record<never, never>, Record<never, never>>,
    '/goldsaying/': RouteRecordInfo<'/goldsaying/', '/goldsaying', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/links/ljs/': RouteRecordInfo<'/links/ljs/', '/links/ljs', Record<never, never>, Record<never, never>>,
    '/links/ljs/interestring': RouteRecordInfo<'/links/ljs/interestring', '/links/ljs/interestring', Record<never, never>, Record<never, never>>,
    '/links/wlr/': RouteRecordInfo<'/links/wlr/', '/links/wlr', Record<never, never>, Record<never, never>>,
    '/links/yzh/': RouteRecordInfo<'/links/yzh/', '/links/yzh', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/2022040101': RouteRecordInfo<'/posts/2022040101', '/posts/2022040101', Record<never, never>, Record<never, never>>,
    '/posts/2024051801': RouteRecordInfo<'/posts/2024051801', '/posts/2024051801', Record<never, never>, Record<never, never>>,
    '/posts/2024052001': RouteRecordInfo<'/posts/2024052001', '/posts/2024052001', Record<never, never>, Record<never, never>>,
    '/posts/2024052101': RouteRecordInfo<'/posts/2024052101', '/posts/2024052101', Record<never, never>, Record<never, never>>,
    '/posts/2024052201': RouteRecordInfo<'/posts/2024052201', '/posts/2024052201', Record<never, never>, Record<never, never>>,
    '/posts/2024052901': RouteRecordInfo<'/posts/2024052901', '/posts/2024052901', Record<never, never>, Record<never, never>>,
    '/posts/2024060301': RouteRecordInfo<'/posts/2024060301', '/posts/2024060301', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
